apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: rabbitmq-web-ui
  namespace: apps

# Common labels applied to all resources
commonLabels:
  app: rabbitmq-web-ui
  managed-by: kustomize

# Resources to include
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - hpa.yaml

# Images to replace
images:
  - name: rmqk8/rabbitmq-web-ui
    newTag: "1.51"
  - name: rmqk8/rabbitmq-web-ui-frontend
    newTag: "1.51"

# ConfigMap generator for additional config
configMapGenerator:
  - name: rabbitmq-web-ui-env
    literals:
      - APP_VERSION=1.0
      - BUILD_DATE=2024-01-01
      - GIT_COMMIT=main

# Namespace for all resources
namespace: apps
