apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    name: apps
    purpose: application-workloads
---
# Note: The apps namespace may already exist in your cluster
# This file is provided for reference and completeness
