apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq-web-ui
  namespace: rabbitmq-webtool-test
  labels:
    app: rabbitmq-web-ui
    component: serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rabbitmq-web-ui
  namespace: rabbitmq-webtool-test
  labels:
    app: rabbitmq-web-ui
    component: role
rules:
# Allow reading ConfigMaps and Secrets for configuration
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
# Allow reading services for service discovery
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
# Allow reading pods for health checks
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rabbitmq-web-ui
  namespace: rabbitmq-webtool-test
  labels:
    app: rabbitmq-web-ui
    component: rolebinding
subjects:
- kind: ServiceAccount
  name: rabbitmq-web-ui
  namespace: rabbitmq-webtool-test
roleRef:
  kind: Role
  name: rabbitmq-web-ui
  apiGroup: rbac.authorization.k8s.io
